routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\HalamanUtamaController;
use App\Http\Controllers\KesehatanController;
use App\Http\Controllers\KeamananController;
use App\Http\Controllers\TransportController;
use App\Http\Controllers\OlahragaController;
use App\Http\Controllers\Pemadam_kebakaranController;
use App\Http\Controllers\Lingkungan_hidupController;


use App\Http\Controllers\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::resource('posts', PostController::class);

Route::get('/', function () {
    return view('welcome');
});


Route::get('dashboard', [HalamanUtamaController::class, 'dashboard'])->middleware('auth');

Route::get('logout', [AuthController::class, 'logout']);

Route::get('home', [HalamanUtamaController::class, 'index']);
Route::get('contact', [HalamanUtamaController::class, 'contact']);

// halaman tentang
Route::get('sejarah', [HalamanUtamaController::class, 'sejarah']);
Route::get('arti-lambang', [HalamanUtamaController::class, 'arti_lambang']);
// halaman layanan
Route::get('layanan/kesehatan ', [HalamanUtamaController::class, 'index_kesehatan']);
Route::get('layanan/kesehatan/{title} ', [HalamanUtamaController::class, 'show_kesehatan']);
Route::get('layanan/keamanan ', [HalamanUtamaController::class, 'index_keamanan']);
Route::get('layanan/keamanan/{title} ', [HalamanUtamaController::class, 'show_keamanan']);
Route::get('layanan/olahraga ', [HalamanUtamaController::class, 'index_olahraga']);
Route::get('layanan/olahraga/{title} ', [HalamanUtamaController::class, 'show_olahraga']);
Route::get('layanan/transport ', [HalamanUtamaController::class, 'index_transport']);
Route::get('layanan/transport/{title} ', [HalamanUtamaController::class, 'show_transport']);
Route::get('layanan/pemadam-kebakaran ', [HalamanUtamaController::class, 'index_pemadam_kebakaran']);
Route::get('layanan/pemadam-kebakaran/{title} ', [HalamanUtamaController::class, 'show_pemadam_kebakaran']);
Route::get('layanan/lingkungan-hidup ', [HalamanUtamaController::class, 'index_lingkungan_hidup']);
Route::get('layanan/lingkungan-hidup/{title} ', [HalamanUtamaController::class, 'show_lingkungan_hidup']);

   
//halaman dashboard
// Route::get('/kesehatan/create', [HalamanUtamaController::class, 'create'])->middleware('password.confirm');

Route::resource('keamanan', KeamananController::class)->middleware('auth');
Route::resource('kesehatan', KesehatanController::class)->middleware('auth');
Route::resource('transport', TransportController::class)->middleware('auth');
Route::resource('pemadam-kebakaran',Pemadam_kebakaranController::class)->middleware('auth');
Route::resource('lingkungan-hidup', Lingkungan_hidupController::class)->middleware('auth');
Route::resource('olahraga', OlahragaController::class)->middleware('auth');


Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/olahraga.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Olahraga extends Model
{
    protected $table = 'Olahraga';
    protected $fillable = ['title','subtitle','details'];
    // public $timestamps = false;
    use HasFactory;
}

app/Http/Controllers/OlahragaController.php
<?php
 
namespace App\Http\Controllers;
 
use Illuminate\Http\Request;
use App\Models\Olahraga;
  
class OlahragaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('password.confirm')->only(['create']);
        // $this->middleware('password.confirm')->only(['show']);
        $this->middleware('password.confirm')->only(['edit']);

    }

    public function index()
    {
        /// mengambil data terakhir dan pagination 5 list
        $Olahragas = Olahraga::get();
        // dd($Olahragas);
        /// mengirimkan variabel $Olahragas ke halaman views Olahragas/index.blade.php
        /// include dengan number index
        return view('layananDashboard.Olahragas.index', compact('Olahragas'));
            // ->with('i', (request()->input('page', 1) - 1) * 5);
    }
  
    public function create()
    {
        /// menampilkan halaman create
        return view('layananDashboard.Olahragas.create');
    }
  
    public function store(Request $request)
    {
        /// membuat validasi untuk title dan content wajib diisi
        $request->validate([
            'title' => 'required',
            'subtitle' => 'required',
            'details' => 'required',
        ]);
         
        /// insert setiap request dari form ke dalam database via model
        /// jika menggunakan metode ini, maka nama field dan nama form harus sama
        Olahraga::create($request->all());
         
        /// redirect jika sukses menyimpan data
        return redirect()->route('olahraga.index')
                        ->with('success','Olahraga created successfully.');
    }
  
    public function show(Olahraga $olahraga)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('Olahragas.show',$post->id) }}
        return view('layananDashboard.Olahragas.show',compact('olahraga'));
    }
  
    public function edit(Olahraga $olahraga)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('Olahragas.edit',$post->id) }}
        return view('layananDashboard.Olahragas.edit',compact('olahraga'));
    }
  
    public function update(Request $request, Olahraga $Olahraga)
    {
        /// membuat validasi untuk title dan content wajib diisi
        // $request->validate([
        //     'title' => 'required',
        //     'content' => 'required',
        // ]);
         
        /// mengubah data berdasarkan request dan parameter yang dikirimkan
        $Olahraga->update($request->all());
         
        /// setelah berhasil mengubah data
        return redirect()->route('olahraga.index')->with('success','Olahraga updated successfully');
    }
  
    public function destroy(Olahraga $olahraga)
    {
        /// melakukan hapus data berdasarkan parameter yang dikirimkan
        $olahraga->delete();
  
        return redirect()->route('olahraga.index')
                        ->with('success','Olahraga deleted successfully');
    }
}

resources/views/layananDashboard/Olahragas/create.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Olahraga</h1>
<p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
    For more information about DataTables, please visit the <a target="_blank"
        href="https://datatables.net">official DataTables documentation</a>.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Post</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('olahraga.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{ route('olahraga.store') }}" method="POST">
            @csrf
        
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        <input type="text" name="title" class="form-control" placeholder="Title">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>subtitle:</strong>
                        <input type="text" name="subtitle" class="form-control" placeholder="subtitle">
                    </div>
                </div>
                
                <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.ckeditor').ckeditor();
                    });
                </script>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>details:</strong>
                        <br>
                        <textarea class="ckeditor" name="details" placeholder="details"></textarea>
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        
        </form>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection

resources/views/layananDashboard/Olahragas/edit.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Olahraga</h1>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Post</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('olahraga.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{ route('olahraga.update',$olahraga->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        <input type="text" name="title" value="{{ $olahraga->title }}" class="form-control" placeholder="Title">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>subtitle:</strong>
                        <input type="text" name="subtitle" value="{{ $olahraga->title }}"  class="form-control" placeholder="subtitle">
                    </div>
                </div>
                
                <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.ckeditor').ckeditor();
                    });
                </script>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>details:</strong>
                        <br>
                        <textarea class="ckeditor" name="details" placeholder="details">{{ $olahraga->details }}</textarea>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">update</button>
                </div>
            </div>
        
        </form>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection

resources/views/layananDashboard/Olahragas/index.blade.php
@extends('layoutsDashboard.index') 
@section('content')
 
 
  <!-- Begin Page Content -->
  <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Tables Olahraga</h1>
<p class="mb-4"><a target="_blank"
        href="https://datatables.net">official DataTables documentation</a>.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        <div class="float-right"  style="margin-buttom:100px"  >
            <a class="btn btn-success" href="{{ route('olahraga.create') }}"> Create Post</a>
        </div>
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            
                <thead>
                    <tr>
                        <th>title</th>
                        <th style="text-align:center; width:20%" >action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>title</th>
                        <th style="text-align:center; width:20%" >action</th>
                    </tr>
                </tfoot>
                <tbody>
                @foreach ($Olahragas as $olahraga)
                    <tr>
                        <td> {{$olahraga->title}} </td>
                        <td class="text-center">
                            <form action="{{ route('olahraga.destroy',$olahraga->id) }}" method="POST">
                                <a class="btn btn-info btn-sm" href="{{ route('olahraga.show',$olahraga->id) }} ">Show  </a>
                                <a class="btn btn-primary btn-sm" href="{{ route('olahraga.edit',$olahraga ->id) }}">Edit</a>         
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                            </form>
                        </td>
                        
                    </tr>
                @endforeach
                    
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->

@endsection

resources/views/layananDashboard/Olahragas/show.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Olahraga</h1>
<p class="mb-4">DataTables is a third party plugin that is used to generate the demo table below.
    For more information about DataTables, please visit the <a target="_blank"
        href="https://datatables.net">official DataTables documentation</a>.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Post</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('olahraga.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $olahraga->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Subtitle:</strong>
                {{ $olahraga->subtitle }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Content:</strong>
                @php
                    echo $olahraga->details
                @endphp
            </div>
        </div>
    </div>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection