routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\HalamanUtamaController;
use App\Http\Controllers\KesehatanController;
use App\Http\Controllers\KeamananController;
use App\Http\Controllers\TransportController;
use App\Http\Controllers\OlahragaController;
use App\Http\Controllers\Pemadam_kebakaranController;
use App\Http\Controllers\Lingkungan_hidupController;


use App\Http\Controllers\AuthController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::resource('posts', PostController::class);

Route::get('/', function () {
    return view('welcome');
});


Route::get('dashboard', [HalamanUtamaController::class, 'dashboard'])->middleware('auth');

Route::get('logout', [AuthController::class, 'logout']);

Route::get('home', [HalamanUtamaController::class, 'index']);
Route::get('contact', [HalamanUtamaController::class, 'contact']);

// halaman tentang
Route::get('sejarah', [HalamanUtamaController::class, 'sejarah']);
Route::get('arti-lambang', [HalamanUtamaController::class, 'arti_lambang']);
// halaman layanan
Route::get('layanan/kesehatan ', [HalamanUtamaController::class, 'index_kesehatan']);
Route::get('layanan/kesehatan/{title} ', [HalamanUtamaController::class, 'show_kesehatan']);
Route::get('layanan/keamanan ', [HalamanUtamaController::class, 'index_keamanan']);
Route::get('layanan/keamanan/{title} ', [HalamanUtamaController::class, 'show_keamanan']);
Route::get('layanan/olahraga ', [HalamanUtamaController::class, 'index_olahraga']);
Route::get('layanan/olahraga/{title} ', [HalamanUtamaController::class, 'show_olahraga']);
Route::get('layanan/transport ', [HalamanUtamaController::class, 'index_transport']);
Route::get('layanan/transport/{title} ', [HalamanUtamaController::class, 'show_transport']);
Route::get('layanan/pemadam-kebakaran ', [HalamanUtamaController::class, 'index_pemadam_kebakaran']);
Route::get('layanan/pemadam-kebakaran/{title} ', [HalamanUtamaController::class, 'show_pemadam_kebakaran']);
Route::get('layanan/lingkungan-hidup ', [HalamanUtamaController::class, 'index_lingkungan_hidup']);
Route::get('layanan/lingkungan-hidup/{title} ', [HalamanUtamaController::class, 'show_lingkungan_hidup']);

   
//halaman dashboard
// Route::get('/kesehatan/create', [HalamanUtamaController::class, 'create'])->middleware('password.confirm');

Route::resource('keamanan', KeamananController::class)->middleware('auth');
Route::resource('kesehatan', KesehatanController::class)->middleware('auth');
Route::resource('transport', TransportController::class)->middleware('auth');
Route::resource('pemadam-kebakaran',Pemadam_kebakaranController::class)->middleware('auth');
Route::resource('lingkungan-hidup', Lingkungan_hidupController::class)->middleware('auth');
Route::resource('olahraga', OlahragaController::class)->middleware('auth');


Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Transport.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Transport extends Model
{
    protected $table = 'transport';
    protected $fillable = ['title','subtitle','details'];
    // public $timestamps = false;
    use HasFactory;
}

app/Http/Controllers/TransportController.php
<?php
 
namespace App\Http\Controllers;
 
use Illuminate\Http\Request;
use App\Models\Transport;
  
class TransportController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('password.confirm')->only(['create']);
        // $this->middleware('password.confirm')->only(['show']);
        $this->middleware('password.confirm')->only(['edit']);

    }

    public function index()
    {
        /// mengambil data terakhir dan pagination 5 list
        $Transports = Transport::get();
        // dd($Transports);
        /// mengirimkan variabel $Transports ke halaman views Transports/index.blade.php
        /// include dengan number index
        return view('layananDashboard.Transports.index', compact('Transports'));
            // ->with('i', (request()->input('page', 1) - 1) * 5);
    }
  
    public function create()
    {
        /// menampilkan halaman create
        return view('layananDashboard.Transports.create');
    }
  
    public function store(Request $request)
    {
        /// membuat validasi untuk title dan content wajib diisi
        $request->validate([
            'title' => 'required',
            'subtitle' => 'required',
            'details' => 'required',
        ]);
         
        /// insert setiap request dari form ke dalam database via model
        /// jika menggunakan metode ini, maka nama field dan nama form harus sama
        Transport::create($request->all());
         
        /// redirect jika sukses menyimpan data
        return redirect()->route('transport.index')
                        ->with('success','Transport created successfully.');
    }
  
    public function show(Transport $transport)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('Transports.show',$post->id) }}
        return view('layananDashboard.Transports.show',compact('transport'));
    }
  
    public function edit(Transport $transport)
    {
        /// dengan menggunakan resource, kita bisa memanfaatkan model sebagai parameter
        /// berdasarkan id yang dipilih
        /// href="{{ route('Transports.edit',$post->id) }}
        return view('layananDashboard.Transports.edit',compact('transport'));
    }
  
    public function update(Request $request, Transport $Transport)
    {
        /// membuat validasi untuk title dan content wajib diisi
        // $request->validate([
        //     'title' => 'required',
        //     'content' => 'required',
        // ]);
         
        /// mengubah data berdasarkan request dan parameter yang dikirimkan
        $Transport->update($request->all());
         
        /// setelah berhasil mengubah data
        return redirect()->route('transport.index')->with('success','Transport updated successfully');
    }
  
    public function destroy(Transport $transport)
    {
        /// melakukan hapus data berdasarkan parameter yang dikirimkan
        $transport->delete();
  
        return redirect()->route('transport.index')
                        ->with('success','Transport deleted successfully');
    }
}

resources/views/layananDashboard/Transports/create.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Transport post</h1>
<p class="mb-4"><a target="_blank"
        href="https://datatables.net">official DataTables documentation</a>.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Post</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('transport.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{ route('transport.store') }}" method="POST">
            @csrf
        
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        <input type="text" name="title" class="form-control" placeholder="Title">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>subtitle:</strong>
                        <input type="text" name="subtitle" class="form-control" placeholder="subtitle">
                    </div>
                </div>
                
                <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.ckeditor').ckeditor();
                    });
                </script>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>details:</strong>
                        <br>
                        <textarea class="ckeditor" name="details" placeholder="details"></textarea>
                    </div>
                </div>
                
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        
        </form>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection

resources/views/layananDashboard/Transports/edit.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Transport post</h1>
<p class="mb-4">.</p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Post</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('transport.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        @if ($errors->any())
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.<br><br>
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{ route('transport.update',$transport->id) }}" method="POST">
            @csrf
            @method('PUT')
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Title:</strong>
                        <input type="text" name="title" value="{{ $transport->title }}" class="form-control" placeholder="Title">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>subtitle:</strong>
                        <input type="text" name="subtitle" value="{{ $transport->title }}"  class="form-control" placeholder="subtitle">
                    </div>
                </div>
                
                <script src="//cdn.ckeditor.com/4.14.1/standard/ckeditor.js"></script>
                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.ckeditor').ckeditor();
                    });
                </script>

                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>details:</strong>
                        <br>
                        <textarea class="ckeditor" name="details" placeholder="details">{{ $transport->details }}</textarea>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">update</button>
                </div>
            </div>
        
        </form>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection

resources/views/layananDashboard/Transports/index.blade.php
@extends('layoutsDashboard.index') 
@section('content')
  <!-- Begin Page Content -->
  <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Tables Transport</h1>
<p class="mb-4"></p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        <div class="float-right"  style="margin-buttom:100px"  >
            <a class="btn btn-success" href="{{ route('transport.create') }}"> Create Post</a>
        </div>
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            
                <thead>
                    <tr>
                        <th>title</th>
                        <th style="text-align:center; width:20%" >action</th>

                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>title</th>
                        <th style="text-align:center; width:20%" >action</th>
                    </tr>
                </tfoot>
                <tbody>
                @foreach ($Transports as $transport)
                    <tr>
                        <td> {{$transport->title}} </td>
                        <td class="text-center">
                            <form action="{{ route('transport.destroy',$transport->id) }}" method="POST">
                                <a class="btn btn-info btn-sm" href="{{ route('transport.show',$transport->id) }} ">Show  </a>
                                <a class="btn btn-primary btn-sm" href="{{ route('transport.edit',$transport ->id) }}">Edit</a>         
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Apakah Anda yakin ingin menghapus data ini?')">Delete</button>
                            </form>
                        </td>
                        
                    </tr>
                @endforeach
                    
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->

@endsection

resources/views/layananDashboard/Transports/show.blade.php
@extends('layoutsDashboard.index')
 
@section('content')

 <!-- Begin Page Content -->
 <div class="container-fluid">

<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Transport post</h1>
<p class="mb-4"> </p>

<!-- DataTales Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <!-- <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6> -->

        
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               
            <div class="row mt-5 mb-5">
            <div class="col-lg-12 margin-tb">
                <div class="float-left">
                    <h2>Create New Post</h2>
                </div>
                <div class="float-right">
                    <a class="btn btn-secondary" href="{{ route('transport.index') }}"> Back</a>
                </div>
            </div>
        </div>
        
        <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $transport->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Subtitle:</strong>
                {{ $transport->subtitle }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Content:</strong>
                @php
                    echo $transport->details
                @endphp
            </div>
        </div>
    </div>
            </table>
        </div>
    </div>
</div>

</div>
<!-- /.container-fluid -->


        


@endsection